# Generated by Django 4.1.7 on 2023-03-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
